import type { MarketDataTicker } from "@/lib/market-data";
import { PRO_ASSET_LIBRARY } from "@/lib/pro-asset-library";

export type AssetCategory =
  | "안전자산"
  | "부동산"
  | "미국ETF"
  | "미국주식"
  | "한국주식"
  | "한국ETF"
  | "코인";

export type ComparisonAssetId = string;

export interface AssetOption {
  accent: string;
  approximationNotice?: string;
  assetTypeBadge?: string;
  amountInfo?: string;
  availabilityNote?: string;
  basis: string;
  category: AssetCategory;
  description: string;
  glow: string;
  id: ComparisonAssetId;
  isAvailable: boolean;
  label: string;
  marketTicker?: MarketDataTicker;
  resultInfoLines?: string[];
  searchTerms: string[];
  selectedSummary?: string;
  shortLabel?: string;
  usesUsdFx?: boolean;
}

function createAsset(option: AssetOption) {
  return option;
}

const GENERATED_ACCENT_BY_CATEGORY: Record<Exclude<AssetCategory, "부동산">, string> = {
  안전자산: "#8E97A4",
  미국ETF: "#6AB8FF",
  미국주식: "#82D6F7",
  한국ETF: "#80C9FF",
  한국주식: "#86C8FF",
  코인: "#F5B95A",
};

const GENERATED_GLOW_BY_CATEGORY: Record<Exclude<AssetCategory, "부동산">, string> = {
  안전자산: "rgba(142, 151, 164, 0.16)",
  미국ETF: "rgba(106, 184, 255, 0.16)",
  미국주식: "rgba(130, 214, 247, 0.16)",
  한국ETF: "rgba(128, 201, 255, 0.16)",
  한국주식: "rgba(134, 200, 255, 0.16)",
  코인: "rgba(245, 185, 90, 0.18)",
};

export const assetCatalog: Record<ComparisonAssetId, AssetOption> = {
  seoul_apt: createAsset({
    accent: "#A78BFA",
    amountInfo: "서울 아파트: 서울 상승 체감을 반영한 비교용 근사값이에요.",
    approximationNotice: "실제 개별 아파트 가격이 아닌 상승 체감형 비교값이에요.",
    assetTypeBadge: "부동산 자산",
    availabilityNote: "실제 개별 아파트 가격이 아닌 비교용 근사값이에요.",
    basis: "서울 상승 체감 반영",
    category: "부동산",
    description: "서울 상승 체감형 비교값",
    glow: "rgba(167, 139, 250, 0.18)",
    id: "seoul_apt",
    isAvailable: true,
    label: "서울 아파트",
    searchTerms: ["서울 아파트", "아파트", "서울 집값", "부동산", "seoul apartment"],
    selectedSummary: "서울 상승 체감형 비교값",
    resultInfoLines: [
      "서울 상승 체감을 반영한 비교용 근사값이에요.",
      "실제 개별 아파트 가격과는 다를 수 있어요.",
      "서울 주택시장 상승 체감이 결과에 반영돼요.",
    ],
    shortLabel: "서울 아파트",
  }),
  gangnam_gu_apt: createAsset({
    accent: "#F59E8B",
    amountInfo: "강남구 아파트: 강남구 상승 체감을 반영한 비교용 근사값이에요.",
    approximationNotice: "실제 개별 아파트 가격이 아닌 상승 체감형 비교값이에요.",
    assetTypeBadge: "부동산 자산",
    availabilityNote: "실제 개별 아파트 가격이 아닌 비교용 근사값이에요.",
    basis: "강남구 상승 체감 반영",
    category: "부동산",
    description: "강남구 상승 체감형 비교값",
    glow: "rgba(245, 158, 139, 0.18)",
    id: "gangnam_gu_apt",
    isAvailable: true,
    label: "강남구 아파트",
    searchTerms: ["강남구 아파트", "강남 아파트", "강남구 집값", "부동산", "gangnam apartment"],
    selectedSummary: "강남구 상승 체감형 비교값",
    resultInfoLines: [
      "강남구 상승 체감을 반영한 비교용 근사값이에요.",
      "실제 개별 아파트 가격과는 차이가 있을 수 있어요.",
      "강남 지역의 더 강한 가격 흐름이 반영돼요.",
    ],
    shortLabel: "강남구 아파트",
  }),
  deposit: createAsset({
    accent: "#8E97A4",
    amountInfo: "예금: 연 2.7% 복리 가정 기준이에요.",
    availabilityNote: "비교용 기준자산 · 고정 연 2.7% 복리 가정 · 실제 은행 상품 아님",
    basis: "고정 연 2.7% 복리 가정 · 실제 은행 상품 아님",
    category: "안전자산",
    description: "연 2.7% 복리 가정",
    glow: "rgba(142, 151, 164, 0.16)",
    id: "deposit",
    isAvailable: true,
    label: "예금",
    resultInfoLines: [
      "연 2.7% 복리 가정 기준이에요.",
      "변동성은 낮지만 장기 기대수익도 제한적인 편이에요.",
    ],
    searchTerms: ["예금", "정기예금", "현금", "deposit", "2.7%", "비교 기준"],
    selectedSummary: "연 2.7% 복리 가정",
    shortLabel: "예금",
  }),
  gold: createAsset({
    accent: "#D7AE58",
    amountInfo: "금: 대표적인 안전자산으로 자주 언급돼요.",
    assetTypeBadge: "실물자산",
    basis: "금 선물 시세 + USD/KRW 환산",
    category: "안전자산",
    description: "대표 안전자산",
    glow: "rgba(215, 174, 88, 0.18)",
    id: "gold",
    isAvailable: true,
    label: "금",
    marketTicker: "GOLD",
    resultInfoLines: [
      "대표적인 안전자산이에요.",
      "위기 국면에서 방어 자산으로 주목받는 경우가 많아요.",
    ],
    searchTerms: ["금", "gold", "안전자산"],
    selectedSummary: "대표 안전자산",
    usesUsdFx: true,
  }),
  usd: createAsset({
    accent: "#7FB2FF",
    assetTypeBadge: "달러 자산",
    basis: "USD/KRW 실제 환율",
    category: "안전자산",
      description: "대표 기축통화 보유 자산",
    glow: "rgba(127, 178, 255, 0.18)",
    id: "usd",
    isAvailable: true,
    label: "미국 달러",
    marketTicker: "USDKRW",
    searchTerms: ["달러", "미국 달러", "usd", "usdkrw"],
  }),
  qqq: createAsset({
    accent: "#63E1D5",
    amountInfo: "QQQ: 미국 기술주 중심 ETF예요.",
    assetTypeBadge: "달러 자산",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
      description: "미국 기술주 중심 ETF",
    glow: "rgba(99, 225, 213, 0.18)",
    id: "qqq",
    isAvailable: true,
    label: "QQQ",
    marketTicker: "QQQ",
    resultInfoLines: [
      "미국 기술주 중심 ETF예요.",
      "대형 기술주의 장기 강세가 결과에 크게 반영됐어요.",
    ],
    searchTerms: ["qqq", "나스닥 etf", "미국 기술주"],
    selectedSummary: "미국 기술주 중심 ETF",
    usesUsdFx: true,
  }),
  voo: createAsset({
    accent: "#6AB8FF",
    amountInfo: "VOO: 미국 대표 대형주 ETF예요.",
    assetTypeBadge: "달러 자산",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
      description: "미국 대표 대형주 ETF",
    glow: "rgba(106, 184, 255, 0.18)",
    id: "voo",
    isAvailable: true,
    label: "VOO",
    marketTicker: "VOO",
    resultInfoLines: [
      "미국 대표 대형주 ETF예요.",
      "미국 전체 대형주 시장 흐름에 가깝게 움직이는 편이에요.",
    ],
    searchTerms: ["voo", "s&p500 etf", "미국 대형주"],
    selectedSummary: "미국 대표 대형주 ETF",
    usesUsdFx: true,
  }),
  vti: createAsset({
    accent: "#8DC7FF",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
    description: "미국 전체 주식시장 ETF",
    glow: "rgba(141, 199, 255, 0.16)",
    id: "vti",
    isAvailable: true,
    label: "VTI",
    marketTicker: "VTI",
    searchTerms: ["vti", "미국 전체시장", "미국 주식시장"],
    usesUsdFx: true,
  }),
  vt: createAsset({
    accent: "#86B0FF",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
    description: "전세계 주식 분산 ETF",
    glow: "rgba(134, 176, 255, 0.16)",
    id: "vt",
    isAvailable: true,
    label: "VT",
    marketTicker: "VT",
    searchTerms: ["vt", "전세계 etf", "글로벌 주식"],
    usesUsdFx: true,
  }),
  vxus: createAsset({
    accent: "#7CB6E8",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
    description: "미국 제외 해외주식 ETF",
    glow: "rgba(124, 182, 232, 0.16)",
    id: "vxus",
    isAvailable: true,
    label: "VXUS",
    marketTicker: "VXUS",
    searchTerms: ["vxus", "해외주식 etf", "미국 제외"],
    usesUsdFx: true,
  }),
  iwm: createAsset({
    accent: "#A0DB78",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
      description: "미국 중소형주 ETF",
    glow: "rgba(160, 219, 120, 0.16)",
    id: "iwm",
    isAvailable: true,
    label: "IWM",
    marketTicker: "IWM",
    searchTerms: ["iwm", "미국 소형주", "러셀 etf"],
    usesUsdFx: true,
  }),
  gld: createAsset({
    accent: "#DAB86D",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
      description: "금에 투자하는 ETF",
    glow: "rgba(218, 184, 109, 0.18)",
    id: "gld",
    isAvailable: true,
    label: "GLD",
    marketTicker: "GLD",
    searchTerms: ["gld", "금 etf", "gold etf"],
    usesUsdFx: true,
  }),
  vnq: createAsset({
    accent: "#9ED4CB",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
      description: "미국 부동산 리츠 ETF",
    glow: "rgba(158, 212, 203, 0.16)",
    id: "vnq",
    isAvailable: true,
    label: "VNQ",
    marketTicker: "VNQ",
    searchTerms: ["vnq", "리츠 etf", "미국 부동산"],
    usesUsdFx: true,
  }),
  soxx: createAsset({
    accent: "#8AF2D8",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국ETF",
    description: "미국 반도체 ETF",
    glow: "rgba(138, 242, 216, 0.18)",
    id: "soxx",
    isAvailable: true,
    label: "SOXX",
    marketTicker: "SOXX",
    searchTerms: ["soxx", "반도체 etf", "미국 반도체"],
    usesUsdFx: true,
  }),
  nvda: createAsset({
    accent: "#67E29A",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "AI 반도체 대표 기업",
    glow: "rgba(103, 226, 154, 0.2)",
    id: "nvda",
    isAvailable: true,
    label: "NVIDIA",
    marketTicker: "NVDA",
    searchTerms: ["엔비디아", "nvidia", "nvda", "ai"],
    usesUsdFx: true,
  }),
  tsla: createAsset({
    accent: "#FF8F6B",
    amountInfo: "Tesla: 미국 전기차·AI 성장주예요.",
    assetTypeBadge: "달러 자산",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
      description: "미국 전기차·AI 성장주",
    glow: "rgba(255, 143, 107, 0.18)",
    id: "tsla",
    isAvailable: true,
    label: "Tesla",
    marketTicker: "TSLA",
    resultInfoLines: [
      "미국 전기차·AI 성장주예요.",
      "상승폭이 클 수 있지만 변동성도 큰 자산이에요.",
    ],
    searchTerms: ["테슬라", "tesla", "tsla"],
    selectedSummary: "미국 전기차·AI 성장주",
    usesUsdFx: true,
  }),
  aapl: createAsset({
    accent: "#C6CED8",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
      description: "아이폰으로 유명한 미국 대표 기업",
    glow: "rgba(198, 206, 216, 0.16)",
    id: "aapl",
    isAvailable: true,
    label: "Apple",
    marketTicker: "AAPL",
    searchTerms: ["애플", "apple", "aapl", "아이폰"],
    usesUsdFx: true,
  }),
  msft: createAsset({
    accent: "#83C3FF",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
      description: "윈도우·AI 대표 기업",
    glow: "rgba(131, 195, 255, 0.16)",
    id: "msft",
    isAvailable: true,
    label: "Microsoft",
    marketTicker: "MSFT",
    searchTerms: ["마이크로소프트", "microsoft", "msft"],
    usesUsdFx: true,
  }),
  amzn: createAsset({
    accent: "#F5B95A",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "미국 대표 전자상거래 기업",
    glow: "rgba(245, 185, 90, 0.16)",
    id: "amzn",
    isAvailable: true,
    label: "Amazon",
    marketTicker: "AMZN",
    searchTerms: ["아마존", "amazon", "amzn"],
    usesUsdFx: true,
  }),
  googl: createAsset({
    accent: "#8FB6FF",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
      description: "구글을 운영하는 미국 기업",
    glow: "rgba(143, 182, 255, 0.16)",
    id: "googl",
    isAvailable: true,
    label: "Alphabet",
    marketTicker: "GOOGL",
    searchTerms: ["알파벳", "구글", "googl", "alphabet", "google"],
    usesUsdFx: true,
  }),
  meta: createAsset({
    accent: "#82D6F7",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "인스타·페이스북 운영 기업",
    glow: "rgba(130, 214, 247, 0.16)",
    id: "meta",
    isAvailable: true,
    label: "Meta",
    marketTicker: "META",
    searchTerms: ["메타", "meta", "facebook", "instagram"],
    usesUsdFx: true,
  }),
  brkb: createAsset({
    accent: "#D9C089",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
      description: "워런 버핏의 대표 투자회사",
    glow: "rgba(217, 192, 137, 0.16)",
    id: "brkb",
    isAvailable: true,
    label: "Berkshire Hathaway",
    marketTicker: "BRKB",
    searchTerms: ["버크셔", "berkshire", "brkb", "버핏"],
    usesUsdFx: true,
  }),
  jpm: createAsset({
    accent: "#86A8D9",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "미국 대표 대형은행",
    glow: "rgba(134, 168, 217, 0.16)",
    id: "jpm",
    isAvailable: true,
    label: "JPMorgan",
    marketTicker: "JPM",
    searchTerms: ["jpm", "jp모건", "jpmorgan"],
    usesUsdFx: true,
  }),
  jnj: createAsset({
    accent: "#9CC7FF",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "미국 대표 헬스케어 기업",
    glow: "rgba(156, 199, 255, 0.16)",
    id: "jnj",
    isAvailable: true,
    label: "Johnson & Johnson",
    marketTicker: "JNJ",
    searchTerms: ["jnj", "존슨앤드존슨", "johnson"],
    usesUsdFx: true,
  }),
  v: createAsset({
    accent: "#89B7FF",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "글로벌 결제 대표 기업",
    glow: "rgba(137, 183, 255, 0.16)",
    id: "v",
    isAvailable: true,
    label: "Visa",
    marketTicker: "V",
    searchTerms: ["비자", "visa", "v"],
    usesUsdFx: true,
  }),
  ma: createAsset({
    accent: "#FF906B",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "글로벌 결제 대표 기업",
    glow: "rgba(255, 144, 107, 0.16)",
    id: "ma",
    isAvailable: true,
    label: "Mastercard",
    marketTicker: "MA",
    searchTerms: ["마스터카드", "mastercard", "ma"],
    usesUsdFx: true,
  }),
  cost: createAsset({
    accent: "#84D8CF",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "미국 대표 창고형 유통기업",
    glow: "rgba(132, 216, 207, 0.16)",
    id: "cost",
    isAvailable: true,
    label: "Costco",
    marketTicker: "COST",
    searchTerms: ["코스트코", "costco", "cost"],
    usesUsdFx: true,
  }),
  pg: createAsset({
    accent: "#B2D6A1",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "생활소비재 대표 기업",
    glow: "rgba(178, 214, 161, 0.16)",
    id: "pg",
    isAvailable: true,
    label: "Procter & Gamble",
    marketTicker: "PG",
    searchTerms: ["pg", "피앤지", "procter"],
    usesUsdFx: true,
  }),
  ko: createAsset({
    accent: "#FF6F80",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "글로벌 음료 대표 기업",
    glow: "rgba(255, 111, 128, 0.16)",
    id: "ko",
    isAvailable: true,
    label: "Coca-Cola",
    marketTicker: "KO",
    searchTerms: ["코카콜라", "coca cola", "ko"],
    usesUsdFx: true,
  }),
  xom: createAsset({
    accent: "#9FAED8",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "미국 대표 에너지 기업",
    glow: "rgba(159, 174, 216, 0.16)",
    id: "xom",
    isAvailable: true,
    label: "Exxon Mobil",
    marketTicker: "XOM",
    searchTerms: ["엑슨모빌", "xom", "exxon"],
    usesUsdFx: true,
  }),
  avgo: createAsset({
    accent: "#7FE3B2",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
      description: "반도체·소프트웨어 대표 기업",
    glow: "rgba(127, 227, 178, 0.16)",
    id: "avgo",
    isAvailable: true,
    label: "Broadcom",
    marketTicker: "AVGO",
    searchTerms: ["브로드컴", "broadcom", "avgo"],
    usesUsdFx: true,
  }),
  amd: createAsset({
    accent: "#7BD7A7",
    basis: "Adjusted close + USD/KRW 환산",
    category: "미국주식",
    description: "미국 대표 반도체 기업",
    glow: "rgba(123, 215, 167, 0.16)",
    id: "amd",
    isAvailable: true,
    label: "AMD",
    marketTicker: "AMD",
    searchTerms: ["amd", "에이엠디", "반도체"],
    usesUsdFx: true,
  }),
  "005930": createAsset({
    accent: "#86C8FF",
    amountInfo: "삼성전자: 한국 대표 반도체 기업이에요.",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 반도체 기업",
    glow: "rgba(134, 200, 255, 0.18)",
    id: "005930",
    isAvailable: true,
    label: "삼성전자",
    marketTicker: "005930",
    resultInfoLines: [
      "한국 대표 반도체 기업이에요.",
      "반도체 업황과 글로벌 경기의 영향을 많이 받아요.",
    ],
    searchTerms: ["삼성전자", "005930", "삼성"],
    selectedSummary: "한국 대표 반도체 기업",
  }),
  "000660": createAsset({
    accent: "#FF7A92",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 메모리 반도체 기업",
    glow: "rgba(255, 122, 146, 0.18)",
    id: "000660",
    isAvailable: true,
    label: "SK하이닉스",
    marketTicker: "000660",
    searchTerms: ["sk하이닉스", "하이닉스", "000660"],
  }),
  "005380": createAsset({
    accent: "#70C7C2",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 자동차 기업",
    glow: "rgba(112, 199, 194, 0.16)",
    id: "005380",
    isAvailable: true,
    label: "현대차",
    marketTicker: "005380",
    searchTerms: ["현대차", "005380", "현대자동차"],
  }),
  "000270": createAsset({
    accent: "#FF9380",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 자동차 브랜드",
    glow: "rgba(255, 147, 128, 0.16)",
    id: "000270",
    isAvailable: true,
    label: "기아",
    marketTicker: "000270",
    searchTerms: ["기아", "000270", "기아차"],
  }),
  "035420": createAsset({
    accent: "#6FD29C",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 인터넷 플랫폼 기업",
    glow: "rgba(111, 210, 156, 0.16)",
    id: "035420",
    isAvailable: true,
    label: "NAVER",
    marketTicker: "035420",
    searchTerms: ["네이버", "naver", "035420"],
  }),
  "035720": createAsset({
    accent: "#F6C05D",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "메신저 기반 플랫폼 기업",
    glow: "rgba(246, 192, 93, 0.16)",
    id: "035720",
    isAvailable: true,
    label: "카카오",
    marketTicker: "035720",
    searchTerms: ["카카오", "kakao", "035720"],
  }),
  "068270": createAsset({
    accent: "#A7D8FF",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 바이오 기업",
    glow: "rgba(167, 216, 255, 0.16)",
    id: "068270",
    isAvailable: true,
    label: "셀트리온",
    marketTicker: "068270",
    searchTerms: ["셀트리온", "068270"],
  }),
  "207940": createAsset({
    accent: "#B8A6FF",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 바이오 생산 기업",
    glow: "rgba(184, 166, 255, 0.16)",
    id: "207940",
    isAvailable: true,
    label: "삼성바이오로직스",
    marketTicker: "207940",
    searchTerms: ["삼성바이오로직스", "207940", "삼바"],
  }),
  "005490": createAsset({
    accent: "#8AB0FF",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 철강 소재 기업",
    glow: "rgba(138, 176, 255, 0.16)",
    id: "005490",
    isAvailable: true,
    label: "POSCO홀딩스",
    marketTicker: "005490",
    searchTerms: ["포스코", "posco", "005490", "posco홀딩스"],
  }),
  "105560": createAsset({
    accent: "#8BC8C1",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 금융지주",
    glow: "rgba(139, 200, 193, 0.16)",
    id: "105560",
    isAvailable: true,
    label: "KB금융",
    marketTicker: "105560",
    searchTerms: ["kb금융", "105560", "국민은행"],
  }),
  "055550": createAsset({
    accent: "#6FC7FF",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 금융지주",
    glow: "rgba(111, 199, 255, 0.16)",
    id: "055550",
    isAvailable: true,
    label: "신한지주",
    marketTicker: "055550",
    searchTerms: ["신한지주", "055550", "신한"],
  }),
  "033780": createAsset({
    accent: "#7FBF97",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 배당·소비재 기업",
    glow: "rgba(127, 191, 151, 0.16)",
    id: "033780",
    isAvailable: true,
    label: "KT&G",
    marketTicker: "033780",
    searchTerms: ["kt&g", "033780", "담배"],
  }),
  "012450": createAsset({
    accent: "#B3C4FF",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "방산·항공 대표 기업",
    glow: "rgba(179, 196, 255, 0.16)",
    id: "012450",
    isAvailable: true,
    label: "한화에어로스페이스",
    marketTicker: "012450",
    searchTerms: ["한화에어로스페이스", "012450", "한화에어로"],
  }),
  "034020": createAsset({
    accent: "#8FD3FF",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "발전설비 대표 기업",
    glow: "rgba(143, 211, 255, 0.16)",
    id: "034020",
    isAvailable: true,
    label: "두산에너빌리티",
    marketTicker: "034020",
    searchTerms: ["두산에너빌리티", "034020", "두산"],
  }),
  "028260": createAsset({
    accent: "#BFC8D9",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 복합지주 기업",
    glow: "rgba(191, 200, 217, 0.16)",
    id: "028260",
    isAvailable: true,
    label: "삼성물산",
    marketTicker: "028260",
    searchTerms: ["삼성물산", "028260"],
  }),
  "003550": createAsset({
    accent: "#C5B1FF",
    basis: "KRW adjusted close",
    category: "한국주식",
    description: "한국 대표 지주회사",
    glow: "rgba(197, 177, 255, 0.16)",
    id: "003550",
    isAvailable: true,
    label: "LG",
    marketTicker: "003550",
    searchTerms: ["lg", "003550", "엘지"],
  }),
  "069500": createAsset({
    accent: "#80C9FF",
    basis: "KRW adjusted close",
    category: "한국ETF",
    description: "한국 대표 지수 ETF",
    glow: "rgba(128, 201, 255, 0.16)",
    id: "069500",
    isAvailable: true,
    label: "KODEX 200",
    marketTicker: "069500",
    searchTerms: ["kodex 200", "069500", "코덱스200"],
  }),
  "360750": createAsset({
    accent: "#6DA8FF",
    availabilityNote: "상장 이력이 10년에 미치지 않아 기본 10년 비교에서는 비활성화돼요.",
    basis: "KRW adjusted close",
    category: "한국ETF",
      description: "미국 대형주 투자 ETF",
    glow: "rgba(109, 168, 255, 0.16)",
    id: "360750",
    isAvailable: false,
    label: "TIGER 미국S&P500",
    marketTicker: "360750",
    searchTerms: ["tiger 미국s&p500", "360750", "tiger sp500"],
  }),
  btc: createAsset({
    accent: "#F5B95A",
    amountInfo: "비트코인: 대표적인 디지털 자산이에요.",
    basis: "BTC-USD 종가 + USD/KRW 환산",
    category: "코인",
    description: "대표 디지털 자산",
    glow: "rgba(245, 185, 90, 0.18)",
    id: "btc",
    isAvailable: true,
    label: "비트코인",
    marketTicker: "BTC",
    resultInfoLines: [
      "대표적인 디지털 자산이에요.",
      "큰 상승 가능성과 매우 큰 변동성을 함께 가져요.",
    ],
    searchTerms: ["비트코인", "bitcoin", "btc"],
    selectedSummary: "대표 디지털 자산",
    usesUsdFx: true,
  }),
  eth: createAsset({
    accent: "#9FAFFF",
    basis: "ETH-USD 종가 + USD/KRW 환산",
    category: "코인",
    description: "대표 스마트컨트랙트 코인",
    glow: "rgba(159, 175, 255, 0.18)",
    id: "eth",
    isAvailable: true,
    label: "이더리움",
    marketTicker: "ETH",
    searchTerms: ["이더리움", "ethereum", "eth"],
    usesUsdFx: true,
  }),
};

for (const asset of PRO_ASSET_LIBRARY) {
  const generatedCategory = asset.category as Exclude<AssetCategory, "부동산">;
  assetCatalog[asset.id] = createAsset({
    accent: GENERATED_ACCENT_BY_CATEGORY[generatedCategory],
    basis:
      asset.category === "미국ETF" || asset.category === "미국주식"
        ? "Adjusted close + USD/KRW 환산"
        : asset.currency === "KRW"
          ? "KRW adjusted close"
          : "Adjusted close",
    category: asset.category,
    description: asset.description,
    glow: GENERATED_GLOW_BY_CATEGORY[generatedCategory],
    id: asset.id,
    isAvailable: true,
    label: asset.label,
    marketTicker: asset.marketTicker,
    searchTerms: [...new Set([asset.label, asset.id, asset.marketTicker, ...(asset.aliases ?? [])])],
    selectedSummary: asset.description,
    usesUsdFx: asset.currency !== "KRW",
  });
}

export const freePlanAssetIds: ComparisonAssetId[] = [
  "deposit",
  "gold",
  "silver",
  "usd",
  "seoul_apt",
  "gangnam_gu_apt",
  "005930",
  "000660",
  "069500",
  "qqq",
  "qqqm",
  "voo",
  "spy",
  "soxl",
  "tqqq",
  "qld",
  "schd",
  "jepq",
  "jepi",
  "smh",
  "soxx",
  "slv",
  "aapl",
  "msft",
  "nvda",
  "tsla",
  "amzn",
  "googl",
  "meta",
  "brkb",
  "btc",
  "eth",
];

const PRO_LIBRARY_ASSET_IDS: ComparisonAssetId[] = PRO_ASSET_LIBRARY.map((asset) => asset.id);

export const assetCategoryOrder: AssetCategory[] = [
  "부동산",
  "안전자산",
  "미국ETF",
  "미국주식",
  "한국주식",
  "한국ETF",
  "코인",
];

const RAW_ASSET_ORDER: ComparisonAssetId[] = [
  "seoul_apt",
  "gangnam_gu_apt",
  "deposit",
  "gold",
  "usd",
  "qqq",
  "qqqm",
  "voo",
  "spy",
  "soxl",
  "tqqq",
  "qld",
  "schd",
  "jepq",
  "jepi",
  "smh",
  "soxx",
  "slv",
  "vti",
  "vt",
  "vxus",
  "iwm",
  "gld",
  "vnq",
  "nvda",
  "tsla",
  "aapl",
  "msft",
  "amzn",
  "googl",
  "meta",
  "brkb",
  "jpm",
  "jnj",
  "v",
  "ma",
  "cost",
  "pg",
  "ko",
  "xom",
  "avgo",
  "amd",
  "005930",
  "000660",
  "005380",
  "000270",
  "035420",
  "035720",
  "068270",
  "207940",
  "005490",
  "105560",
  "055550",
  "033780",
  "012450",
  "034020",
  "028260",
  "003550",
  "069500",
  "360750",
  "btc",
  "eth",
  ...PRO_LIBRARY_ASSET_IDS,
];

export const assetOrder: ComparisonAssetId[] = Array.from(new Set(RAW_ASSET_ORDER));

export const selectableAssetIds = assetOrder.filter((assetId) => assetCatalog[assetId].isAvailable);
export const disabledAssetIds = assetOrder.filter((assetId) => !assetCatalog[assetId].isAvailable);

export const featuredAssetIds: ComparisonAssetId[] = freePlanAssetIds;

export const defaultSelectedAssetIds: ComparisonAssetId[] = [];

export const amountPresets = [
  { label: "500만원", value: 5_000_000 },
  { label: "1,000만원", value: 10_000_000 },
  { label: "5,000만원", value: 50_000_000 },
  { label: "1억", value: 100_000_000 },
] as const;

export const trustNotes = [
  "실제 과거 시계열을 바탕으로 봐요.",
  "미국 주식·ETF는 adjusted close를 우선 사용해요.",
  "한국 주식·ETF도 adjusted close를 기준으로 봐요.",
  "코인과 금은 실제 종가 흐름을 사용해요.",
  "서울 아파트는 서울 상승 체감을 반영한 비교값이에요.",
  "강남구 아파트는 강남구 상승 체감을 반영한 비교값이에요.",
  "예금은 연 2.7% 복리로 단순화한 기준값이에요.",
  "미국 자산과 달러 자산은 같은 날짜 환율로 원화 환산해요.",
  "예금은 실제 은행 상품이나 실시간 금리 피드가 아니에요.",
  "10년 데이터가 부족한 자산은 기본 비교에서 비활성화돼요.",
] as const;

export const trustSummary =
  "과거 흐름 기준 · 서울/강남구 아파트 비교 지원 · 예금은 연 2.7% 복리 가정";

export const DEFAULT_AMOUNT = 10_000_000;
export const INPUT_MAX_AMOUNT = 1_000_000_000_000;
export const FIXED_YEARS = 10;
export const RACE_DURATION_MS = 18_000;
export const PRO_LIBRARY_ASSET_COUNT = assetOrder.length;
