/**
 * Current market-cap snapshot used by the home search.
 * US: US-listed operating companies, one representative share class per issuer.
 * KR: KOSPI/KOSDAQ common stocks, excluding preferred shares and exchange-traded products.
 */
export const MARKET_CAP_SNAPSHOT_DATE = "2026-07-10" as const;

export type MarketCapMarket = "US" | "KR";
export type MarketCapExchange = "NASDAQ" | "NYSE" | "KOSPI" | "KOSDAQ";
export type MarketCapCurrency = "USD" | "KRW";

export interface MarketCapCompany {
  id: string;
  label: string;
  aliases?: readonly string[];
  market: MarketCapMarket;
  rank: number;
  rankAsOf: typeof MARKET_CAP_SNAPSHOT_DATE;
  exchange: MarketCapExchange;
  marketTicker: string;
  yahooSymbol: string;
  currency: MarketCapCurrency;
}

export const US_TOP_100_COMPANIES = [
  { id: "nvda", label: "NVIDIA", aliases: ["엔비디아"], market: "US", rank: 1, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "NVDA", yahooSymbol: "NVDA", currency: "USD" },
  { id: "aapl", label: "Apple", aliases: ["애플"], market: "US", rank: 2, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "AAPL", yahooSymbol: "AAPL", currency: "USD" },
  { id: "googl", label: "Alphabet", aliases: ["알파벳", "구글"], market: "US", rank: 3, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "GOOGL", yahooSymbol: "GOOGL", currency: "USD" },
  { id: "msft", label: "Microsoft", aliases: ["마이크로소프트"], market: "US", rank: 4, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "MSFT", yahooSymbol: "MSFT", currency: "USD" },
  { id: "amzn", label: "Amazon", aliases: ["아마존"], market: "US", rank: 5, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "AMZN", yahooSymbol: "AMZN", currency: "USD" },
  { id: "tsm", label: "TSMC", aliases: ["대만반도체", "Taiwan Semiconductor"], market: "US", rank: 6, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "TSM", yahooSymbol: "TSM", currency: "USD" },
  { id: "avgo", label: "Broadcom", aliases: ["브로드컴"], market: "US", rank: 7, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "AVGO", yahooSymbol: "AVGO", currency: "USD" },
  { id: "spcx", label: "SpaceX", aliases: ["스페이스X", "스페이스엑스"], market: "US", rank: 8, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "SPCX", yahooSymbol: "SPCX", currency: "USD" },
  { id: "meta", label: "Meta Platforms", aliases: ["메타", "페이스북"], market: "US", rank: 9, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "META", yahooSymbol: "META", currency: "USD" },
  { id: "tsla", label: "Tesla", aliases: ["테슬라"], market: "US", rank: 10, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "TSLA", yahooSymbol: "TSLA", currency: "USD" },
  { id: "lly", label: "Eli Lilly", aliases: ["일라이 릴리", "일라이릴리"], market: "US", rank: 11, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "LLY", yahooSymbol: "LLY", currency: "USD" },
  { id: "mu", label: "Micron Technology", aliases: ["마이크론"], market: "US", rank: 12, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "MU", yahooSymbol: "MU", currency: "USD" },
  { id: "brkb", label: "Berkshire Hathaway", aliases: ["버크셔 해서웨이", "버크셔해서웨이", "BRK.B"], market: "US", rank: 13, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "BRKB", yahooSymbol: "BRK-B", currency: "USD" },
  { id: "amd", label: "Advanced Micro Devices", aliases: ["AMD", "에이엠디"], market: "US", rank: 14, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "AMD", yahooSymbol: "AMD", currency: "USD" },
  { id: "wmt", label: "Walmart", aliases: ["월마트"], market: "US", rank: 15, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "WMT", yahooSymbol: "WMT", currency: "USD" },
  { id: "jpm", label: "JPMorgan Chase", aliases: ["JP모간", "제이피모간"], market: "US", rank: 16, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "JPM", yahooSymbol: "JPM", currency: "USD" },
  { id: "asml", label: "ASML", aliases: ["에이에스엠엘"], market: "US", rank: 17, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "ASML", yahooSymbol: "ASML", currency: "USD" },
  { id: "v", label: "Visa", aliases: ["비자"], market: "US", rank: 18, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "V", yahooSymbol: "V", currency: "USD" },
  { id: "jnj", label: "Johnson & Johnson", aliases: ["존슨앤드존슨", "J&J"], market: "US", rank: 19, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "JNJ", yahooSymbol: "JNJ", currency: "USD" },
  { id: "xom", label: "Exxon Mobil", aliases: ["엑슨모빌"], market: "US", rank: 20, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "XOM", yahooSymbol: "XOM", currency: "USD" },
  { id: "intc", label: "Intel", aliases: ["인텔"], market: "US", rank: 21, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "INTC", yahooSymbol: "INTC", currency: "USD" },
  { id: "amat", label: "Applied Materials", aliases: ["어플라이드 머티어리얼즈"], market: "US", rank: 22, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "AMAT", yahooSymbol: "AMAT", currency: "USD" },
  { id: "csco", label: "Cisco Systems", aliases: ["시스코"], market: "US", rank: 23, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "CSCO", yahooSymbol: "CSCO", currency: "USD" },
  { id: "ma", label: "Mastercard", aliases: ["마스터카드"], market: "US", rank: 24, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "MA", yahooSymbol: "MA", currency: "USD" },
  { id: "cat", label: "Caterpillar", aliases: ["캐터필러"], market: "US", rank: 25, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "CAT", yahooSymbol: "CAT", currency: "USD" },
  { id: "abbv", label: "AbbVie", aliases: ["애브비"], market: "US", rank: 26, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "ABBV", yahooSymbol: "ABBV", currency: "USD" },
  { id: "lrcx", label: "Lam Research", aliases: ["램리서치"], market: "US", rank: 27, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "LRCX", yahooSymbol: "LRCX", currency: "USD" },
  { id: "bac", label: "Bank of America", aliases: ["뱅크오브아메리카", "BOA"], market: "US", rank: 28, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "BAC", yahooSymbol: "BAC", currency: "USD" },
  { id: "cost", label: "Costco Wholesale", aliases: ["코스트코"], market: "US", rank: 29, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "COST", yahooSymbol: "COST", currency: "USD" },
  { id: "orcl", label: "Oracle", aliases: ["오라클"], market: "US", rank: 30, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "ORCL", yahooSymbol: "ORCL", currency: "USD" },
  { id: "unh", label: "UnitedHealth Group", aliases: ["유나이티드헬스"], market: "US", rank: 31, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "UNH", yahooSymbol: "UNH", currency: "USD" },
  { id: "ge", label: "GE Aerospace", aliases: ["GE 에어로스페이스"], market: "US", rank: 32, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "GE", yahooSymbol: "GE", currency: "USD" },
  { id: "ko", label: "Coca-Cola", aliases: ["코카콜라"], market: "US", rank: 33, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "KO", yahooSymbol: "KO", currency: "USD" },
  { id: "cvx", label: "Chevron", aliases: ["셰브론", "쉐브론"], market: "US", rank: 34, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "CVX", yahooSymbol: "CVX", currency: "USD" },
  { id: "ms", label: "Morgan Stanley", aliases: ["모건스탠리"], market: "US", rank: 35, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "MS", yahooSymbol: "MS", currency: "USD" },
  { id: "arm", label: "Arm Holdings", aliases: ["ARM", "암 홀딩스"], market: "US", rank: 36, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "ARM", yahooSymbol: "ARM", currency: "USD" },
  { id: "pg", label: "Procter & Gamble", aliases: ["프록터앤갬블", "P&G"], market: "US", rank: 37, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "PG", yahooSymbol: "PG", currency: "USD" },
  { id: "hd", label: "Home Depot", aliases: ["홈디포"], market: "US", rank: 38, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "HD", yahooSymbol: "HD", currency: "USD" },
  { id: "hsbc", label: "HSBC Holdings", aliases: ["HSBC"], market: "US", rank: 39, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "HSBC", yahooSymbol: "HSBC", currency: "USD" },
  { id: "gs", label: "Goldman Sachs", aliases: ["골드만삭스"], market: "US", rank: 40, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "GS", yahooSymbol: "GS", currency: "USD" },
  { id: "nflx", label: "Netflix", aliases: ["넷플릭스"], market: "US", rank: 41, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "NFLX", yahooSymbol: "NFLX", currency: "USD" },
  { id: "mrk", label: "Merck", aliases: ["머크"], market: "US", rank: 42, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "MRK", yahooSymbol: "MRK", currency: "USD" },
  { id: "pltr", label: "Palantir Technologies", aliases: ["팔란티어"], market: "US", rank: 43, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "PLTR", yahooSymbol: "PLTR", currency: "USD" },
  { id: "klac", label: "KLA", aliases: ["케이엘에이"], market: "US", rank: 44, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "KLAC", yahooSymbol: "KLAC", currency: "USD" },
  { id: "nvs", label: "Novartis", aliases: ["노바티스"], market: "US", rank: 45, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "NVS", yahooSymbol: "NVS", currency: "USD" },
  { id: "ry", label: "Royal Bank of Canada", aliases: ["로열뱅크오브캐나다", "RBC"], market: "US", rank: 46, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "RY", yahooSymbol: "RY", currency: "USD" },
  { id: "gev", label: "GE Vernova", aliases: ["GE 버노바"], market: "US", rank: 47, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "GEV", yahooSymbol: "GEV", currency: "USD" },
  { id: "sndk", label: "Sandisk", aliases: ["샌디스크"], market: "US", rank: 48, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "SNDK", yahooSymbol: "SNDK", currency: "USD" },
  { id: "txn", label: "Texas Instruments", aliases: ["텍사스 인스트루먼트"], market: "US", rank: 49, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "TXN", yahooSymbol: "TXN", currency: "USD" },
  { id: "pm", label: "Philip Morris International", aliases: ["필립모리스"], market: "US", rank: 50, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "PM", yahooSymbol: "PM", currency: "USD" },
  { id: "dell", label: "Dell Technologies", aliases: ["델 테크놀로지스", "델"], market: "US", rank: 51, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "DELL", yahooSymbol: "DELL", currency: "USD" },
  { id: "tm", label: "Toyota Motor", aliases: ["토요타", "도요타"], market: "US", rank: 52, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "TM", yahooSymbol: "TM", currency: "USD" },
  { id: "ibm", label: "IBM", aliases: ["아이비엠"], market: "US", rank: 53, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "IBM", yahooSymbol: "IBM", currency: "USD" },
  { id: "wfc", label: "Wells Fargo", aliases: ["웰스파고"], market: "US", rank: 54, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "WFC", yahooSymbol: "WFC", currency: "USD" },
  { id: "azn", label: "AstraZeneca", aliases: ["아스트라제네카"], market: "US", rank: 55, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "AZN", yahooSymbol: "AZN", currency: "USD" },
  { id: "panw", label: "Palo Alto Networks", aliases: ["팔로알토 네트웍스"], market: "US", rank: 56, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "PANW", yahooSymbol: "PANW", currency: "USD" },
  { id: "rtx", label: "RTX", aliases: ["레이시온"], market: "US", rank: 57, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "RTX", yahooSymbol: "RTX", currency: "USD" },
  { id: "baba", label: "Alibaba Group", aliases: ["알리바바"], market: "US", rank: 58, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "BABA", yahooSymbol: "BABA", currency: "USD" },
  { id: "mufg", label: "Mitsubishi UFJ Financial Group", aliases: ["미쓰비시UFJ", "미쓰비시 UFJ"], market: "US", rank: 59, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "MUFG", yahooSymbol: "MUFG", currency: "USD" },
  { id: "lin", label: "Linde", aliases: ["린데"], market: "US", rank: 60, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "LIN", yahooSymbol: "LIN", currency: "USD" },
  { id: "c", label: "Citigroup", aliases: ["씨티그룹", "시티그룹"], market: "US", rank: 61, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "C", yahooSymbol: "C", currency: "USD" },
  { id: "axp", label: "American Express", aliases: ["아메리칸 익스프레스", "아멕스"], market: "US", rank: 62, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "AXP", yahooSymbol: "AXP", currency: "USD" },
  { id: "anet", label: "Arista Networks", aliases: ["아리스타 네트웍스"], market: "US", rank: 63, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "ANET", yahooSymbol: "ANET", currency: "USD" },
  { id: "shel", label: "Shell", aliases: ["셸", "쉘"], market: "US", rank: 64, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "SHEL", yahooSymbol: "SHEL", currency: "USD" },
  { id: "nvo", label: "Novo Nordisk", aliases: ["노보 노디스크", "노보노디스크"], market: "US", rank: 65, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "NVO", yahooSymbol: "NVO", currency: "USD" },
  { id: "bhp", label: "BHP", aliases: ["비에이치피"], market: "US", rank: 66, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "BHP", yahooSymbol: "BHP", currency: "USD" },
  { id: "mrvl", label: "Marvell Technology", aliases: ["마벨 테크놀로지", "마벨"], market: "US", rank: 67, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "MRVL", yahooSymbol: "MRVL", currency: "USD" },
  { id: "stx", label: "Seagate Technology", aliases: ["씨게이트"], market: "US", rank: 68, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "STX", yahooSymbol: "STX", currency: "USD" },
  { id: "san", label: "Banco Santander", aliases: ["산탄데르"], market: "US", rank: 69, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "SAN", yahooSymbol: "SAN", currency: "USD" },
  { id: "tmus", label: "T-Mobile US", aliases: ["T모바일", "티모바일"], market: "US", rank: 70, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "TMUS", yahooSymbol: "TMUS", currency: "USD" },
  { id: "wdc", label: "Western Digital", aliases: ["웨스턴디지털"], market: "US", rank: 71, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "WDC", yahooSymbol: "WDC", currency: "USD" },
  { id: "qcom", label: "Qualcomm", aliases: ["퀄컴"], market: "US", rank: 72, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "QCOM", yahooSymbol: "QCOM", currency: "USD" },
  { id: "td", label: "Toronto-Dominion Bank", aliases: ["토론토도미니언은행", "TD은행"], market: "US", rank: 73, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "TD", yahooSymbol: "TD", currency: "USD" },
  { id: "amgn", label: "Amgen", aliases: ["암젠"], market: "US", rank: 74, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "AMGN", yahooSymbol: "AMGN", currency: "USD" },
  { id: "tmo", label: "Thermo Fisher Scientific", aliases: ["써모피셔 사이언티픽", "써모 피셔"], market: "US", rank: 75, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "TMO", yahooSymbol: "TMO", currency: "USD" },
  { id: "aph", label: "Amphenol", aliases: ["암페놀"], market: "US", rank: 76, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "APH", yahooSymbol: "APH", currency: "USD" },
  { id: "mcd", label: "McDonald's", aliases: ["맥도날드"], market: "US", rank: 77, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "MCD", yahooSymbol: "MCD", currency: "USD" },
  { id: "sap", label: "SAP", aliases: ["에스에이피"], market: "US", rank: 78, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "SAP", yahooSymbol: "SAP", currency: "USD" },
  { id: "adi", label: "Analog Devices", aliases: ["아날로그 디바이스"], market: "US", rank: 79, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "ADI", yahooSymbol: "ADI", currency: "USD" },
  { id: "crwd", label: "CrowdStrike", aliases: ["크라우드스트라이크"], market: "US", rank: 80, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "CRWD", yahooSymbol: "CRWD", currency: "USD" },
  { id: "pep", label: "PepsiCo", aliases: ["펩시코", "펩시"], market: "US", rank: 81, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "PEP", yahooSymbol: "PEP", currency: "USD" },
  { id: "nee", label: "NextEra Energy", aliases: ["넥스트에라 에너지"], market: "US", rank: 82, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "NEE", yahooSymbol: "NEE", currency: "USD" },
  { id: "schw", label: "Charles Schwab", aliases: ["찰스슈왑"], market: "US", rank: 83, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "SCHW", yahooSymbol: "SCHW", currency: "USD" },
  { id: "vz", label: "Verizon", aliases: ["버라이즌"], market: "US", rank: 84, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "VZ", yahooSymbol: "VZ", currency: "USD" },
  { id: "ba", label: "Boeing", aliases: ["보잉"], market: "US", rank: 85, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "BA", yahooSymbol: "BA", currency: "USD" },
  { id: "tte", label: "TotalEnergies", aliases: ["토탈에너지스"], market: "US", rank: 86, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "TTE", yahooSymbol: "TTE", currency: "USD" },
  { id: "unp", label: "Union Pacific", aliases: ["유니언퍼시픽"], market: "US", rank: 87, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "UNP", yahooSymbol: "UNP", currency: "USD" },
  { id: "app", label: "AppLovin", aliases: ["앱러빈", "앱로빈"], market: "US", rank: 88, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "APP", yahooSymbol: "APP", currency: "USD" },
  { id: "tjx", label: "TJX Companies", aliases: ["티제이엑스"], market: "US", rank: 89, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "TJX", yahooSymbol: "TJX", currency: "USD" },
  { id: "dis", label: "Walt Disney", aliases: ["월트 디즈니", "디즈니"], market: "US", rank: 90, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "DIS", yahooSymbol: "DIS", currency: "USD" },
  { id: "glw", label: "Corning", aliases: ["코닝"], market: "US", rank: 91, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "GLW", yahooSymbol: "GLW", currency: "USD" },
  { id: "smfg", label: "Sumitomo Mitsui Financial Group", aliases: ["스미토모 미쓰이"], market: "US", rank: 92, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "SMFG", yahooSymbol: "SMFG", currency: "USD" },
  { id: "abt", label: "Abbott Laboratories", aliases: ["애보트"], market: "US", rank: 93, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "ABT", yahooSymbol: "ABT", currency: "USD" },
  { id: "well", label: "Welltower", aliases: ["웰타워"], market: "US", rank: 94, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "WELL", yahooSymbol: "WELL", currency: "USD" },
  { id: "gild", label: "Gilead Sciences", aliases: ["길리어드 사이언스"], market: "US", rank: 95, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "GILD", yahooSymbol: "GILD", currency: "USD" },
  { id: "ubs", label: "UBS Group", aliases: ["유비에스"], market: "US", rank: 96, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "UBS", yahooSymbol: "UBS", currency: "USD" },
  { id: "blk", label: "BlackRock", aliases: ["블랙록"], market: "US", rank: 97, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "BLK", yahooSymbol: "BLK", currency: "USD" },
  { id: "ibkr", label: "Interactive Brokers", aliases: ["인터랙티브 브로커스"], market: "US", rank: 98, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "IBKR", yahooSymbol: "IBKR", currency: "USD" },
  { id: "shop", label: "Shopify", aliases: ["쇼피파이"], market: "US", rank: 99, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NASDAQ", marketTicker: "SHOP", yahooSymbol: "SHOP", currency: "USD" },
  { id: "de", label: "Deere & Company", aliases: ["디어", "존디어"], market: "US", rank: 100, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "NYSE", marketTicker: "DE", yahooSymbol: "DE", currency: "USD" },
] as const satisfies readonly MarketCapCompany[];

export const KR_TOP_100_COMPANIES = [
  { id: "005930", label: "삼성전자", market: "KR", rank: 1, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "005930", yahooSymbol: "005930.KS", currency: "KRW" },
  { id: "000660", label: "SK하이닉스", market: "KR", rank: 2, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "000660", yahooSymbol: "000660.KS", currency: "KRW" },
  { id: "402340", label: "SK스퀘어", market: "KR", rank: 3, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "402340", yahooSymbol: "402340.KS", currency: "KRW" },
  { id: "009150", label: "삼성전기", market: "KR", rank: 4, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "009150", yahooSymbol: "009150.KS", currency: "KRW" },
  { id: "005380", label: "현대차", aliases: ["현대자동차"], market: "KR", rank: 5, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "005380", yahooSymbol: "005380.KS", currency: "KRW" },
  { id: "373220", label: "LG에너지솔루션", aliases: ["LG엔솔"], market: "KR", rank: 6, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "373220", yahooSymbol: "373220.KS", currency: "KRW" },
  { id: "032830", label: "삼성생명", market: "KR", rank: 7, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "032830", yahooSymbol: "032830.KS", currency: "KRW" },
  { id: "105560", label: "KB금융", aliases: ["KB금융지주"], market: "KR", rank: 8, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "105560", yahooSymbol: "105560.KS", currency: "KRW" },
  { id: "207940", label: "삼성바이오로직스", aliases: ["삼성바이오"], market: "KR", rank: 9, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "207940", yahooSymbol: "207940.KS", currency: "KRW" },
  { id: "028260", label: "삼성물산", market: "KR", rank: 10, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "028260", yahooSymbol: "028260.KS", currency: "KRW" },
  { id: "000270", label: "기아", aliases: ["기아자동차"], market: "KR", rank: 11, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "000270", yahooSymbol: "000270.KS", currency: "KRW" },
  { id: "329180", label: "HD현대중공업", aliases: ["현대중공업"], market: "KR", rank: 12, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "329180", yahooSymbol: "329180.KS", currency: "KRW" },
  { id: "055550", label: "신한지주", aliases: ["신한금융지주"], market: "KR", rank: 13, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "055550", yahooSymbol: "055550.KS", currency: "KRW" },
  { id: "034020", label: "두산에너빌리티", market: "KR", rank: 14, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "034020", yahooSymbol: "034020.KS", currency: "KRW" },
  { id: "012450", label: "한화에어로스페이스", aliases: ["한화에어로"], market: "KR", rank: 15, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "012450", yahooSymbol: "012450.KS", currency: "KRW" },
  { id: "034730", label: "SK", aliases: ["SK주식회사"], market: "KR", rank: 16, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "034730", yahooSymbol: "034730.KS", currency: "KRW" },
  { id: "012330", label: "현대모비스", market: "KR", rank: 17, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "012330", yahooSymbol: "012330.KS", currency: "KRW" },
  { id: "068270", label: "셀트리온", market: "KR", rank: 18, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "068270", yahooSymbol: "068270.KS", currency: "KRW" },
  { id: "086790", label: "하나금융지주", aliases: ["하나금융"], market: "KR", rank: 19, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "086790", yahooSymbol: "086790.KS", currency: "KRW" },
  { id: "006400", label: "삼성SDI", market: "KR", rank: 20, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "006400", yahooSymbol: "006400.KS", currency: "KRW" },
  { id: "267260", label: "HD현대일렉트릭", aliases: ["현대일렉트릭"], market: "KR", rank: 21, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "267260", yahooSymbol: "267260.KS", currency: "KRW" },
  { id: "010120", label: "LS ELECTRIC", aliases: ["LS일렉트릭"], market: "KR", rank: 22, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "010120", yahooSymbol: "010120.KS", currency: "KRW" },
  { id: "035420", label: "NAVER", aliases: ["네이버"], market: "KR", rank: 23, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "035420", yahooSymbol: "035420.KS", currency: "KRW" },
  { id: "066570", label: "LG전자", market: "KR", rank: 24, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "066570", yahooSymbol: "066570.KS", currency: "KRW" },
  { id: "000810", label: "삼성화재", market: "KR", rank: 25, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "000810", yahooSymbol: "000810.KS", currency: "KRW" },
  { id: "298040", label: "효성중공업", market: "KR", rank: 26, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "298040", yahooSymbol: "298040.KS", currency: "KRW" },
  { id: "042660", label: "한화오션", aliases: ["대우조선해양"], market: "KR", rank: 27, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "042660", yahooSymbol: "042660.KS", currency: "KRW" },
  { id: "005490", label: "POSCO홀딩스", aliases: ["포스코홀딩스"], market: "KR", rank: 28, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "005490", yahooSymbol: "005490.KS", currency: "KRW" },
  { id: "009540", label: "HD한국조선해양", aliases: ["한국조선해양"], market: "KR", rank: 29, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "009540", yahooSymbol: "009540.KS", currency: "KRW" },
  { id: "006800", label: "미래에셋증권", market: "KR", rank: 30, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "006800", yahooSymbol: "006800.KS", currency: "KRW" },
  { id: "015760", label: "한국전력", aliases: ["한전"], market: "KR", rank: 31, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "015760", yahooSymbol: "015760.KS", currency: "KRW" },
  { id: "316140", label: "우리금융지주", aliases: ["우리금융"], market: "KR", rank: 32, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "316140", yahooSymbol: "316140.KS", currency: "KRW" },
  { id: "000150", label: "두산", market: "KR", rank: 33, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "000150", yahooSymbol: "000150.KS", currency: "KRW" },
  { id: "010130", label: "고려아연", market: "KR", rank: 34, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "010130", yahooSymbol: "010130.KS", currency: "KRW" },
  { id: "042700", label: "한미반도체", market: "KR", rank: 35, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "042700", yahooSymbol: "042700.KS", currency: "KRW" },
  { id: "010140", label: "삼성중공업", market: "KR", rank: 36, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "010140", yahooSymbol: "010140.KS", currency: "KRW" },
  { id: "064350", label: "현대로템", market: "KR", rank: 37, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "064350", yahooSymbol: "064350.KS", currency: "KRW" },
  { id: "138040", label: "메리츠금융지주", aliases: ["메리츠금융"], market: "KR", rank: 38, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "138040", yahooSymbol: "138040.KS", currency: "KRW" },
  { id: "017670", label: "SK텔레콤", aliases: ["SKT"], market: "KR", rank: 39, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "017670", yahooSymbol: "017670.KS", currency: "KRW" },
  { id: "051910", label: "LG화학", market: "KR", rank: 40, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "051910", yahooSymbol: "051910.KS", currency: "KRW" },
  { id: "011200", label: "HMM", aliases: ["현대상선"], market: "KR", rank: 41, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "011200", yahooSymbol: "011200.KS", currency: "KRW" },
  { id: "033780", label: "KT&G", aliases: ["케이티앤지"], market: "KR", rank: 42, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "033780", yahooSymbol: "033780.KS", currency: "KRW" },
  { id: "011070", label: "LG이노텍", market: "KR", rank: 43, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "011070", yahooSymbol: "011070.KS", currency: "KRW" },
  { id: "096770", label: "SK이노베이션", market: "KR", rank: 44, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "096770", yahooSymbol: "096770.KS", currency: "KRW" },
  { id: "196170", label: "알테오젠", market: "KR", rank: 45, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSDAQ", marketTicker: "196170", yahooSymbol: "196170.KQ", currency: "KRW" },
  { id: "024110", label: "기업은행", aliases: ["IBK기업은행"], market: "KR", rank: 46, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "024110", yahooSymbol: "024110.KS", currency: "KRW" },
  { id: "079550", label: "LIG디펜스앤에어로스페이스", aliases: ["LIG넥스원"], market: "KR", rank: 47, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "079550", yahooSymbol: "079550.KS", currency: "KRW" },
  { id: "267250", label: "HD현대", aliases: ["현대중공업지주"], market: "KR", rank: 48, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "267250", yahooSymbol: "267250.KS", currency: "KRW" },
  { id: "035720", label: "카카오", market: "KR", rank: 49, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "035720", yahooSymbol: "035720.KS", currency: "KRW" },
  { id: "018260", label: "삼성에스디에스", aliases: ["삼성SDS"], market: "KR", rank: 50, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "018260", yahooSymbol: "018260.KS", currency: "KRW" },
  { id: "003550", label: "LG", aliases: ["LG그룹"], market: "KR", rank: 51, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "003550", yahooSymbol: "003550.KS", currency: "KRW" },
  { id: "010950", label: "S-Oil", aliases: ["에쓰오일"], market: "KR", rank: 52, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "010950", yahooSymbol: "010950.KS", currency: "KRW" },
  { id: "086280", label: "현대글로비스", market: "KR", rank: 53, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "086280", yahooSymbol: "086280.KS", currency: "KRW" },
  { id: "047810", label: "한국항공우주", aliases: ["KAI"], market: "KR", rank: 54, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "047810", yahooSymbol: "047810.KS", currency: "KRW" },
  { id: "278470", label: "에이피알", aliases: ["APR"], market: "KR", rank: 55, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "278470", yahooSymbol: "278470.KS", currency: "KRW" },
  { id: "030200", label: "KT", aliases: ["케이티"], market: "KR", rank: 56, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "030200", yahooSymbol: "030200.KS", currency: "KRW" },
  { id: "272210", label: "한화시스템", market: "KR", rank: 57, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "272210", yahooSymbol: "272210.KS", currency: "KRW" },
  { id: "003670", label: "포스코퓨처엠", market: "KR", rank: 58, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "003670", yahooSymbol: "003670.KS", currency: "KRW" },
  { id: "071050", label: "한국금융지주", market: "KR", rank: 59, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "071050", yahooSymbol: "071050.KS", currency: "KRW" },
  { id: "307950", label: "현대오토에버", market: "KR", rank: 60, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "307950", yahooSymbol: "307950.KS", currency: "KRW" },
  { id: "000720", label: "현대건설", market: "KR", rank: 61, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "000720", yahooSymbol: "000720.KS", currency: "KRW" },
  { id: "247540", label: "에코프로비엠", market: "KR", rank: 62, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSDAQ", marketTicker: "247540", yahooSymbol: "247540.KQ", currency: "KRW" },
  { id: "086520", label: "에코프로", market: "KR", rank: 63, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSDAQ", marketTicker: "086520", yahooSymbol: "086520.KQ", currency: "KRW" },
  { id: "005940", label: "NH투자증권", market: "KR", rank: 64, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "005940", yahooSymbol: "005940.KS", currency: "KRW" },
  { id: "259960", label: "크래프톤", market: "KR", rank: 65, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "259960", yahooSymbol: "259960.KS", currency: "KRW" },
  { id: "323410", label: "카카오뱅크", market: "KR", rank: 66, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "323410", yahooSymbol: "323410.KS", currency: "KRW" },
  { id: "006260", label: "LS", aliases: ["LS그룹"], market: "KR", rank: 67, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "006260", yahooSymbol: "006260.KS", currency: "KRW" },
  { id: "005830", label: "DB손해보험", market: "KR", rank: 68, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "005830", yahooSymbol: "005830.KS", currency: "KRW" },
  { id: "016360", label: "삼성증권", market: "KR", rank: 69, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "016360", yahooSymbol: "016360.KS", currency: "KRW" },
  { id: "003490", label: "대한항공", market: "KR", rank: 70, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "003490", yahooSymbol: "003490.KS", currency: "KRW" },
  { id: "0126Z0", label: "삼성에피스홀딩스", aliases: ["Samsung Epis Holdings"], market: "KR", rank: 71, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "0126Z0", yahooSymbol: "0126Z0.KS", currency: "KRW" },
  { id: "352820", label: "하이브", aliases: ["HYBE"], market: "KR", rank: 72, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "352820", yahooSymbol: "352820.KS", currency: "KRW" },
  { id: "180640", label: "한진칼", market: "KR", rank: 73, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "180640", yahooSymbol: "180640.KS", currency: "KRW" },
  { id: "036930", label: "주성엔지니어링", market: "KR", rank: 74, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSDAQ", marketTicker: "036930", yahooSymbol: "036930.KQ", currency: "KRW" },
  { id: "161390", label: "한국타이어앤테크놀로지", aliases: ["한국타이어"], market: "KR", rank: 75, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "161390", yahooSymbol: "161390.KS", currency: "KRW" },
  { id: "443060", label: "HD현대마린솔루션", market: "KR", rank: 76, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "443060", yahooSymbol: "443060.KS", currency: "KRW" },
  { id: "039490", label: "키움증권", market: "KR", rank: 77, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "039490", yahooSymbol: "039490.KS", currency: "KRW" },
  { id: "277810", label: "레인보우로보틱스", market: "KR", rank: 78, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSDAQ", marketTicker: "277810", yahooSymbol: "277810.KQ", currency: "KRW" },
  { id: "047050", label: "포스코인터내셔널", market: "KR", rank: 79, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "047050", yahooSymbol: "047050.KS", currency: "KRW" },
  { id: "028050", label: "삼성E&A", aliases: ["삼성엔지니어링"], market: "KR", rank: 80, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "028050", yahooSymbol: "028050.KS", currency: "KRW" },
  { id: "003230", label: "삼양식품", market: "KR", rank: 81, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "003230", yahooSymbol: "003230.KS", currency: "KRW" },
  { id: "950160", label: "코오롱티슈진", market: "KR", rank: 82, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSDAQ", marketTicker: "950160", yahooSymbol: "950160.KQ", currency: "KRW" },
  { id: "007660", label: "이수페타시스", market: "KR", rank: 83, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "007660", yahooSymbol: "007660.KS", currency: "KRW" },
  { id: "078930", label: "GS", aliases: ["GS그룹"], market: "KR", rank: 84, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "078930", yahooSymbol: "078930.KS", currency: "KRW" },
  { id: "090430", label: "아모레퍼시픽", market: "KR", rank: 85, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "090430", yahooSymbol: "090430.KS", currency: "KRW" },
  { id: "047040", label: "대우건설", market: "KR", rank: 86, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "047040", yahooSymbol: "047040.KS", currency: "KRW" },
  { id: "064400", label: "LG씨엔에스", aliases: ["LG CNS"], market: "KR", rank: 87, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "064400", yahooSymbol: "064400.KS", currency: "KRW" },
  { id: "000880", label: "한화", market: "KR", rank: 88, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "000880", yahooSymbol: "000880.KS", currency: "KRW" },
  { id: "326030", label: "SK바이오팜", market: "KR", rank: 89, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "326030", yahooSymbol: "326030.KS", currency: "KRW" },
  { id: "021240", label: "코웨이", market: "KR", rank: 90, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "021240", yahooSymbol: "021240.KS", currency: "KRW" },
  { id: "032640", label: "LG유플러스", aliases: ["LGU+", "LG U+"], market: "KR", rank: 91, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "032640", yahooSymbol: "032640.KS", currency: "KRW" },
  { id: "267270", label: "HD건설기계", market: "KR", rank: 92, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "267270", yahooSymbol: "267270.KS", currency: "KRW" },
  { id: "240810", label: "원익IPS", market: "KR", rank: 93, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSDAQ", marketTicker: "240810", yahooSymbol: "240810.KQ", currency: "KRW" },
  { id: "241560", label: "두산밥캣", market: "KR", rank: 94, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "241560", yahooSymbol: "241560.KS", currency: "KRW" },
  { id: "353200", label: "대덕전자", market: "KR", rank: 95, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "353200", yahooSymbol: "353200.KS", currency: "KRW" },
  { id: "004170", label: "신세계", market: "KR", rank: 96, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "004170", yahooSymbol: "004170.KS", currency: "KRW" },
  { id: "001440", label: "대한전선", market: "KR", rank: 97, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "001440", yahooSymbol: "001440.KS", currency: "KRW" },
  { id: "062040", label: "산일전기", market: "KR", rank: 98, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "062040", yahooSymbol: "062040.KS", currency: "KRW" },
  { id: "058470", label: "리노공업", market: "KR", rank: 99, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSDAQ", marketTicker: "058470", yahooSymbol: "058470.KQ", currency: "KRW" },
  { id: "029780", label: "삼성카드", market: "KR", rank: 100, rankAsOf: MARKET_CAP_SNAPSHOT_DATE, exchange: "KOSPI", marketTicker: "029780", yahooSymbol: "029780.KS", currency: "KRW" },
] as const satisfies readonly MarketCapCompany[];

export const MARKET_CAP_COMPANIES: readonly MarketCapCompany[] = [
  ...US_TOP_100_COMPANIES,
  ...KR_TOP_100_COMPANIES,
];

export const MARKET_CAP_COMPANY_IDS: readonly string[] = MARKET_CAP_COMPANIES.map(
  (company) => company.id,
);
