import type { AssetCategory, ComparisonAssetId } from "@/lib/home-content";
import type { CurrencyCode, MarketDataTicker } from "@/lib/market-data";

export interface ProAssetDefinition {
  aliases?: string[];
  category: AssetCategory;
  currency: CurrencyCode;
  description: string;
  id: ComparisonAssetId;
  label: string;
  marketTicker: MarketDataTicker;
  priceBasis?: "adjusted_close" | "close";
  yahooSymbol: string;
}

export const PRO_ASSET_LIBRARY: ProAssetDefinition[] = [
  { aliases: ["다우 etf"], category: "미국ETF", currency: "USD", description: "미국 대표 우량주 ETF", id: "dia", label: "DIA", marketTicker: "DIA", yahooSymbol: "DIA" },
  { aliases: ["s&p500 etf"], category: "미국ETF", currency: "USD", description: "미국 S&P500 ETF", id: "ivv", label: "IVV", marketTicker: "IVV", yahooSymbol: "IVV" },
  { aliases: ["sp500 etf"], category: "미국ETF", currency: "USD", description: "미국 S&P500 저비용 ETF", id: "splg", label: "SPLG", marketTicker: "SPLG", yahooSymbol: "SPLG" },
  { aliases: ["배당 etf"], category: "미국ETF", currency: "USD", description: "미국 배당주 ETF", id: "schd", label: "SCHD", marketTicker: "SCHD", yahooSymbol: "SCHD" },
  { aliases: ["성장주 etf"], category: "미국ETF", currency: "USD", description: "미국 성장주 ETF", id: "vug", label: "VUG", marketTicker: "VUG", yahooSymbol: "VUG" },
  { aliases: ["가치주 etf"], category: "미국ETF", currency: "USD", description: "미국 가치주 ETF", id: "vtv", label: "VTV", marketTicker: "VTV", yahooSymbol: "VTV" },
  { aliases: ["기술주 섹터 etf"], category: "미국ETF", currency: "USD", description: "미국 기술주 섹터 ETF", id: "xlk", label: "XLK", marketTicker: "XLK", yahooSymbol: "XLK" },
  { aliases: ["에너지 etf"], category: "미국ETF", currency: "USD", description: "미국 에너지 ETF", id: "xle", label: "XLE", marketTicker: "XLE", yahooSymbol: "XLE" },
  { aliases: ["금융 etf"], category: "미국ETF", currency: "USD", description: "미국 금융 ETF", id: "xlf", label: "XLF", marketTicker: "XLF", yahooSymbol: "XLF" },
  { aliases: ["산업재 etf"], category: "미국ETF", currency: "USD", description: "미국 산업재 ETF", id: "xli", label: "XLI", marketTicker: "XLI", yahooSymbol: "XLI" },
  { aliases: ["헬스케어 etf"], category: "미국ETF", currency: "USD", description: "미국 헬스케어 ETF", id: "xlv", label: "XLV", marketTicker: "XLV", yahooSymbol: "XLV" },
  { aliases: ["소비재 etf"], category: "미국ETF", currency: "USD", description: "미국 필수소비재 ETF", id: "xlp", label: "XLP", marketTicker: "XLP", yahooSymbol: "XLP" },
  { aliases: ["소비 etf"], category: "미국ETF", currency: "USD", description: "미국 경기소비재 ETF", id: "xly", label: "XLY", marketTicker: "XLY", yahooSymbol: "XLY" },
  { aliases: ["유틸리티 etf"], category: "미국ETF", currency: "USD", description: "미국 유틸리티 ETF", id: "xlu", label: "XLU", marketTicker: "XLU", yahooSymbol: "XLU" },
  { aliases: ["소재 etf"], category: "미국ETF", currency: "USD", description: "미국 소재 ETF", id: "xlb", label: "XLB", marketTicker: "XLB", yahooSymbol: "XLB" },
  { aliases: ["리츠 etf"], category: "미국ETF", currency: "USD", description: "미국 부동산 ETF", id: "xlre", label: "XLRE", marketTicker: "XLRE", yahooSymbol: "XLRE" },
  { aliases: ["혁신 etf"], category: "미국ETF", currency: "USD", description: "미국 혁신 성장 ETF", id: "arkk", label: "ARKK", marketTicker: "ARKK", yahooSymbol: "ARKK" },
  { aliases: ["금 etf"], category: "미국ETF", currency: "USD", description: "금 현물 추종 ETF", id: "iau", label: "IAU", marketTicker: "IAU", yahooSymbol: "IAU" },
  { aliases: ["은 etf"], category: "미국ETF", currency: "USD", description: "은 현물 추종 ETF", id: "slv", label: "SLV", marketTicker: "SLV", yahooSymbol: "SLV" },
  { aliases: ["미국 국채"], category: "미국ETF", currency: "USD", description: "미국 장기국채 ETF", id: "tlt", label: "TLT", marketTicker: "TLT", yahooSymbol: "TLT" },
  { aliases: ["단기 국채"], category: "미국ETF", currency: "USD", description: "미국 단기국채 ETF", id: "shy", label: "SHY", marketTicker: "SHY", yahooSymbol: "SHY" },
  { aliases: ["회사채 etf"], category: "미국ETF", currency: "USD", description: "미국 하이일드채 ETF", id: "hyg", label: "HYG", marketTicker: "HYG", yahooSymbol: "HYG" },
  { aliases: ["선진국 etf"], category: "미국ETF", currency: "USD", description: "미국 제외 선진국 ETF", id: "efa", label: "EFA", marketTicker: "EFA", yahooSymbol: "EFA" },
  { aliases: ["신흥국 etf"], category: "미국ETF", currency: "USD", description: "신흥국 주식 ETF", id: "eem", label: "EEM", marketTicker: "EEM", yahooSymbol: "EEM" },
  { aliases: ["중국 인터넷 etf"], category: "미국ETF", currency: "USD", description: "중국 인터넷 ETF", id: "kweb", label: "KWEB", marketTicker: "KWEB", yahooSymbol: "KWEB" },
  { aliases: ["반도체 etf"], category: "미국ETF", currency: "USD", description: "미국 반도체 ETF", id: "smh", label: "SMH", marketTicker: "SMH", yahooSymbol: "SMH" },
  { aliases: ["바이오 etf"], category: "미국ETF", currency: "USD", description: "미국 바이오 ETF", id: "xbi", label: "XBI", marketTicker: "XBI", yahooSymbol: "XBI" },
  { aliases: ["비트코인 etf"], category: "미국ETF", currency: "USD", description: "미국 비트코인 선물 ETF", id: "bito", label: "BITO", marketTicker: "BITO", yahooSymbol: "BITO" },
  { aliases: ["로봇 etf", "robotics etf", "ai etf"], category: "미국ETF", currency: "USD", description: "로봇·AI 기업을 담은 ETF", id: "botz", label: "BOTZ", marketTicker: "BOTZ", yahooSymbol: "BOTZ" },
  { aliases: ["양자컴퓨터 etf", "quantum etf"], category: "미국ETF", currency: "USD", description: "양자컴퓨팅 테마 ETF", id: "qtum", label: "QTUM", marketTicker: "QTUM", yahooSymbol: "QTUM" },
  { aliases: ["넷플릭스"], category: "미국주식", currency: "USD", description: "글로벌 스트리밍 기업", id: "nflx", label: "Netflix", marketTicker: "NFLX", yahooSymbol: "NFLX" },
  { aliases: ["오라클"], category: "미국주식", currency: "USD", description: "미국 기업용 소프트웨어 기업", id: "orcl", label: "Oracle", marketTicker: "ORCL", yahooSymbol: "ORCL" },
  { aliases: ["세일즈포스"], category: "미국주식", currency: "USD", description: "미국 CRM 소프트웨어 기업", id: "crm", label: "Salesforce", marketTicker: "CRM", yahooSymbol: "CRM" },
  { aliases: ["어도비"], category: "미국주식", currency: "USD", description: "디자인 소프트웨어 대표 기업", id: "adbe", label: "Adobe", marketTicker: "ADBE", yahooSymbol: "ADBE" },
  { aliases: ["디즈니"], category: "미국주식", currency: "USD", description: "글로벌 콘텐츠 기업", id: "dis", label: "Disney", marketTicker: "DIS", yahooSymbol: "DIS" },
  { aliases: ["월마트"], category: "미국주식", currency: "USD", description: "미국 대표 유통 기업", id: "wmt", label: "Walmart", marketTicker: "WMT", yahooSymbol: "WMT" },
  { aliases: ["맥도날드"], category: "미국주식", currency: "USD", description: "글로벌 외식 대표 기업", id: "mcd", label: "McDonald's", marketTicker: "MCD", yahooSymbol: "MCD" },
  { aliases: ["나이키"], category: "미국주식", currency: "USD", description: "글로벌 스포츠 브랜드", id: "nke", label: "Nike", marketTicker: "NKE", yahooSymbol: "NKE" },
  { aliases: ["펩시"], category: "미국주식", currency: "USD", description: "미국 대표 식음료 기업", id: "pep", label: "PepsiCo", marketTicker: "PEP", yahooSymbol: "PEP" },
  { aliases: ["애브비"], category: "미국주식", currency: "USD", description: "미국 대표 제약 기업", id: "abbv", label: "AbbVie", marketTicker: "ABBV", yahooSymbol: "ABBV" },
  { aliases: ["머크"], category: "미국주식", currency: "USD", description: "미국 대표 제약 기업", id: "mrk", label: "Merck", marketTicker: "MRK", yahooSymbol: "MRK" },
  { aliases: ["화이자"], category: "미국주식", currency: "USD", description: "미국 대표 제약 기업", id: "pfe", label: "Pfizer", marketTicker: "PFE", yahooSymbol: "PFE" },
  { aliases: ["유나이티드헬스"], category: "미국주식", currency: "USD", description: "미국 대표 헬스케어 기업", id: "unh", label: "UnitedHealth", marketTicker: "UNH", yahooSymbol: "UNH" },
  { aliases: ["홈디포"], category: "미국주식", currency: "USD", description: "미국 대표 주택개선 기업", id: "hd", label: "Home Depot", marketTicker: "HD", yahooSymbol: "HD" },
  { aliases: ["로우스"], category: "미국주식", currency: "USD", description: "미국 주택개선 유통 기업", id: "low", label: "Lowe's", marketTicker: "LOW", yahooSymbol: "LOW" },
  { aliases: ["캐터필러"], category: "미국주식", currency: "USD", description: "미국 대표 산업 장비 기업", id: "cat", label: "Caterpillar", marketTicker: "CAT", yahooSymbol: "CAT" },
  { aliases: ["ge"], category: "미국주식", currency: "USD", description: "미국 대표 산업 복합 기업", id: "ge", label: "GE Aerospace", marketTicker: "GE", yahooSymbol: "GE" },
  { aliases: ["보잉"], category: "미국주식", currency: "USD", description: "미국 대표 항공기 기업", id: "ba", label: "Boeing", marketTicker: "BA", yahooSymbol: "BA" },
  { aliases: ["tsm", "tsmc"], category: "미국주식", currency: "USD", description: "글로벌 파운드리 대표 기업", id: "tsm", label: "TSMC", marketTicker: "TSM", yahooSymbol: "TSM" },
  { aliases: ["ibm"], category: "미국주식", currency: "USD", description: "미국 전통 기술 기업", id: "ibm", label: "IBM", marketTicker: "IBM", yahooSymbol: "IBM" },
  { aliases: ["시스코"], category: "미국주식", currency: "USD", description: "미국 네트워크 장비 기업", id: "csco", label: "Cisco", marketTicker: "CSCO", yahooSymbol: "CSCO" },
  { aliases: ["인텔"], category: "미국주식", currency: "USD", description: "미국 대표 반도체 기업", id: "intc", label: "Intel", marketTicker: "INTC", yahooSymbol: "INTC" },
  { aliases: ["퀄컴"], category: "미국주식", currency: "USD", description: "미국 모바일 반도체 기업", id: "qcom", label: "Qualcomm", marketTicker: "QCOM", yahooSymbol: "QCOM" },
  { aliases: ["텍사스인스트루먼트"], category: "미국주식", currency: "USD", description: "미국 아날로그 반도체 기업", id: "txn", label: "Texas Instruments", marketTicker: "TXN", yahooSymbol: "TXN" },
  { aliases: ["어플라이드머티리얼즈"], category: "미국주식", currency: "USD", description: "반도체 장비 대표 기업", id: "amat", label: "Applied Materials", marketTicker: "AMAT", yahooSymbol: "AMAT" },
  { aliases: ["린데"], category: "미국주식", currency: "USD", description: "글로벌 산업가스 기업", id: "lin", label: "Linde", marketTicker: "LIN", yahooSymbol: "LIN" },
  { aliases: ["코노코필립스"], category: "미국주식", currency: "USD", description: "미국 에너지 기업", id: "cop", label: "ConocoPhillips", marketTicker: "COP", yahooSymbol: "COP" },
  { aliases: ["셰브론"], category: "미국주식", currency: "USD", description: "미국 대표 에너지 기업", id: "cvx", label: "Chevron", marketTicker: "CVX", yahooSymbol: "CVX" },
  { aliases: ["골드만삭스"], category: "미국주식", currency: "USD", description: "미국 투자은행 대표 기업", id: "gs", label: "Goldman Sachs", marketTicker: "GS", yahooSymbol: "GS" },
  { aliases: ["뱅크오브아메리카"], category: "미국주식", currency: "USD", description: "미국 대형 은행", id: "bac", label: "Bank of America", marketTicker: "BAC", yahooSymbol: "BAC" },
  { aliases: ["블랙록"], category: "미국주식", currency: "USD", description: "글로벌 자산운용 대표 기업", id: "blk", label: "BlackRock", marketTicker: "BLK", yahooSymbol: "BLK" },
  { aliases: ["일라이릴리"], category: "미국주식", currency: "USD", description: "미국 대표 바이오 제약 기업", id: "lly", label: "Eli Lilly", marketTicker: "LLY", yahooSymbol: "LLY" },
  { aliases: ["도요타"], category: "미국주식", currency: "USD", description: "글로벌 자동차 대표 기업", id: "tm", label: "Toyota", marketTicker: "TM", yahooSymbol: "TM" },
  { aliases: ["소니"], category: "미국주식", currency: "USD", description: "일본 대표 콘텐츠·전자 기업", id: "sony", label: "Sony", marketTicker: "SONY", yahooSymbol: "SONY" },
  { aliases: ["sap"], category: "미국주식", currency: "USD", description: "유럽 대표 기업용 소프트웨어 기업", id: "sap", label: "SAP", marketTicker: "SAP", yahooSymbol: "SAP" },
  { aliases: ["노보노디스크"], category: "미국주식", currency: "USD", description: "글로벌 비만·당뇨 치료 대표 기업", id: "nvo", label: "Novo Nordisk", marketTicker: "NVO", yahooSymbol: "NVO" },
  { aliases: ["s&p500 etf", "sp500 etf"], category: "미국ETF", currency: "USD", description: "미국 S&P500 대표 ETF", id: "spy", label: "SPY", marketTicker: "SPY", yahooSymbol: "SPY" },
  { aliases: ["나스닥100 etf", "nasdaq100 etf"], category: "미국ETF", currency: "USD", description: "나스닥100 저비용 ETF", id: "qqqm", label: "QQQM", marketTicker: "QQQM", yahooSymbol: "QQQM" },
  { aliases: ["soxl", "반도체 3배", "레버리지 반도체"], category: "미국ETF", currency: "USD", description: "미국 반도체 3배 레버리지 ETF", id: "soxl", label: "SOXL", marketTicker: "SOXL", yahooSymbol: "SOXL" },
  { aliases: ["tqqq", "나스닥 3배", "레버리지 나스닥"], category: "미국ETF", currency: "USD", description: "나스닥100 3배 레버리지 ETF", id: "tqqq", label: "TQQQ", marketTicker: "TQQQ", yahooSymbol: "TQQQ" },
  { aliases: ["qld", "나스닥 2배", "레버리지 qqq"], category: "미국ETF", currency: "USD", description: "나스닥100 2배 레버리지 ETF", id: "qld", label: "QLD", marketTicker: "QLD", yahooSymbol: "QLD" },
  { aliases: ["upro", "s&p500 3배", "레버리지 s&p500"], category: "미국ETF", currency: "USD", description: "S&P500 3배 레버리지 ETF", id: "upro", label: "UPRO", marketTicker: "UPRO", yahooSymbol: "UPRO" },
  { aliases: ["월배당 etf", "jepi"], category: "미국ETF", currency: "USD", description: "월배당 중심 인컴 ETF", id: "jepi", label: "JEPI", marketTicker: "JEPI", yahooSymbol: "JEPI" },
  { aliases: ["jepq", "나스닥 월배당", "월배당 etf"], category: "미국ETF", currency: "USD", description: "나스닥 기반 월배당 인컴 ETF", id: "jepq", label: "JEPQ", marketTicker: "JEPQ", yahooSymbol: "JEPQ" },
  { aliases: ["tsll", "테슬라 2배", "테슬라 레버리지"], category: "미국ETF", currency: "USD", description: "테슬라 2배 레버리지 ETF", id: "tsll", label: "TSLL", marketTicker: "TSLL", yahooSymbol: "TSLL" },
  { aliases: ["nvdl", "엔비디아 2배", "엔비디아 레버리지"], category: "미국ETF", currency: "USD", description: "엔비디아 2배 레버리지 ETF", id: "nvdl", label: "NVDL", marketTicker: "NVDL", yahooSymbol: "NVDL" },
  { aliases: ["은", "silver"], category: "안전자산", currency: "USD", description: "금보다 변동성이 큰 대표 귀금속 자산", id: "silver", label: "은", marketTicker: "SILVER", priceBasis: "close", yahooSymbol: "SI=F" },
  { aliases: ["팔란티어", "pltr"], category: "미국주식", currency: "USD", description: "AI·데이터 분석 소프트웨어 기업", id: "pltr", label: "Palantir", marketTicker: "PLTR", yahooSymbol: "PLTR" },
  { aliases: ["asml", "반도체 장비", "노광장비"], category: "미국주식", currency: "USD", description: "첨단 반도체 장비 대표 기업", id: "asml", label: "ASML", marketTicker: "ASML", yahooSymbol: "ASML" },
  { aliases: ["arm", "ARM 홀딩스", "반도체 설계"], category: "미국주식", currency: "USD", description: "반도체 설계 IP 대표 기업", id: "arm", label: "ARM", marketTicker: "ARM", yahooSymbol: "ARM" },
  { aliases: ["마이크론", "mu", "메모리", "HBM"], category: "미국주식", currency: "USD", description: "미국 대표 메모리 반도체 기업", id: "mu", label: "Micron", marketTicker: "MU", yahooSymbol: "MU" },
  { aliases: ["마벨", "mrvl", "데이터센터 반도체"], category: "미국주식", currency: "USD", description: "데이터센터 반도체 성장주", id: "mrvl", label: "Marvell", marketTicker: "MRVL", yahooSymbol: "MRVL" },
  { aliases: ["램리서치", "lrcx", "반도체 장비"], category: "미국주식", currency: "USD", description: "반도체 공정 장비 대표 기업", id: "lrcx", label: "Lam Research", marketTicker: "LRCX", yahooSymbol: "LRCX" },
  { aliases: ["kla", "klac", "반도체 검사"], category: "미국주식", currency: "USD", description: "반도체 검사·계측 장비 기업", id: "klac", label: "KLA", marketTicker: "KLAC", yahooSymbol: "KLAC" },
  { aliases: ["슈퍼마이크로", "smci", "AI 서버"], category: "미국주식", currency: "USD", description: "AI 서버 인프라 성장주", id: "smci", label: "Super Micro Computer", marketTicker: "SMCI", yahooSymbol: "SMCI" },
  { aliases: ["스노우플레이크", "snow", "데이터 클라우드"], category: "미국주식", currency: "USD", description: "데이터 클라우드 소프트웨어 기업", id: "snow", label: "Snowflake", marketTicker: "SNOW", yahooSymbol: "SNOW" },
  { aliases: ["크라우드스트라이크", "crwd", "사이버보안"], category: "미국주식", currency: "USD", description: "클라우드 보안 대표 기업", id: "crwd", label: "CrowdStrike", marketTicker: "CRWD", yahooSymbol: "CRWD" },
  { aliases: ["아이온큐", "ionq", "양자컴퓨터"], category: "미국주식", currency: "USD", description: "양자컴퓨터 대표 성장주", id: "ionq", label: "IonQ", marketTicker: "IONQ", yahooSymbol: "IONQ" },
  { aliases: ["리게티", "rgti", "양자컴퓨터"], category: "미국주식", currency: "USD", description: "양자컴퓨터 고변동 성장주", id: "rgti", label: "Rigetti", marketTicker: "RGTI", yahooSymbol: "RGTI" },
  { aliases: ["디웨이브", "qbts", "양자컴퓨터"], category: "미국주식", currency: "USD", description: "양자컴퓨팅 하드웨어 기업", id: "qbts", label: "D-Wave Quantum", marketTicker: "QBTS", yahooSymbol: "QBTS" },
  { aliases: ["인튜이티브서지컬", "isrg", "수술로봇"], category: "미국주식", currency: "USD", description: "수술 로봇 대표 기업", id: "isrg", label: "Intuitive Surgical", marketTicker: "ISRG", yahooSymbol: "ISRG" },
  { aliases: ["록웰오토메이션", "rok", "공장자동화"], category: "미국주식", currency: "USD", description: "산업 자동화 대표 기업", id: "rok", label: "Rockwell Automation", marketTicker: "ROK", yahooSymbol: "ROK" },
  { aliases: ["테라다인", "ter", "반도체 테스트", "로봇"], category: "미국주식", currency: "USD", description: "반도체 테스트·자동화 기업", id: "ter", label: "Teradyne", marketTicker: "TER", yahooSymbol: "TER" },
  { aliases: ["컨스텔레이션에너지", "ceg", "원전", "전력"], category: "미국주식", currency: "USD", description: "원전·전력 인프라 대표 기업", id: "ceg", label: "Constellation Energy", marketTicker: "CEG", yahooSymbol: "CEG" },
  { aliases: ["넥스트에라에너지", "nee", "재생에너지"], category: "미국주식", currency: "USD", description: "미국 대표 유틸리티·재생에너지 기업", id: "nee", label: "NextEra Energy", marketTicker: "NEE", yahooSymbol: "NEE" },
  { aliases: ["비스트라", "vst", "전력", "AI 전력"], category: "미국주식", currency: "USD", description: "전력 수요 테마로 주목받는 기업", id: "vst", label: "Vistra", marketTicker: "VST", yahooSymbol: "VST" },
  { aliases: ["퍼스트솔라", "fslr", "태양광"], category: "미국주식", currency: "USD", description: "미국 태양광 대표 기업", id: "fslr", label: "First Solar", marketTicker: "FSLR", yahooSymbol: "FSLR" },
  { aliases: ["하나금융지주", "086790"], category: "한국주식", currency: "KRW", description: "한국 대표 금융지주", id: "086790", label: "하나금융지주", marketTicker: "086790", yahooSymbol: "086790.KS" },
  { aliases: ["한국전력", "015760", "한전"], category: "한국주식", currency: "KRW", description: "한국 대표 전력 공기업", id: "015760", label: "한국전력", marketTicker: "015760", yahooSymbol: "015760.KS" },
  { aliases: ["LG화학", "051910"], category: "한국주식", currency: "KRW", description: "한국 대표 화학·배터리 소재 기업", id: "051910", label: "LG화학", marketTicker: "051910", yahooSymbol: "051910.KS" },
  { aliases: ["SK이노베이션", "096770"], category: "한국주식", currency: "KRW", description: "배터리·에너지 대표 기업", id: "096770", label: "SK이노베이션", marketTicker: "096770", yahooSymbol: "096770.KS" },
  { aliases: ["현대모비스", "012330"], category: "한국주식", currency: "KRW", description: "자동차 부품 대표 기업", id: "012330", label: "현대모비스", marketTicker: "012330", yahooSymbol: "012330.KS" },
  { aliases: ["삼성SDI", "006400"], category: "한국주식", currency: "KRW", description: "한국 대표 배터리 기업", id: "006400", label: "삼성SDI", marketTicker: "006400", yahooSymbol: "006400.KS" },
  { aliases: ["고려아연", "010130"], category: "한국주식", currency: "KRW", description: "비철금속 대표 기업", id: "010130", label: "고려아연", marketTicker: "010130", yahooSymbol: "010130.KS" },
  { aliases: ["한미반도체", "042700"], category: "한국주식", currency: "KRW", description: "반도체 장비 대표 기업", id: "042700", label: "한미반도체", marketTicker: "042700", yahooSymbol: "042700.KS" },
  { aliases: ["HPSP", "403870", "반도체 장비"], category: "한국주식", currency: "KRW", description: "반도체 고압 수소 어닐링 장비 기업", id: "403870", label: "HPSP", marketTicker: "403870", yahooSymbol: "403870.KQ" },
  { aliases: ["리노공업", "058470", "반도체 테스트"], category: "한국주식", currency: "KRW", description: "반도체 테스트 소켓 대표 기업", id: "058470", label: "리노공업", marketTicker: "058470", yahooSymbol: "058470.KQ" },
  { aliases: ["ISC", "095340", "반도체 테스트"], category: "한국주식", currency: "KRW", description: "반도체 테스트 소켓 기업", id: "095340", label: "ISC", marketTicker: "095340", yahooSymbol: "095340.KQ" },
  { aliases: ["DB하이텍", "000990", "파운드리"], category: "한국주식", currency: "KRW", description: "한국 시스템 반도체 파운드리 기업", id: "000990", label: "DB하이텍", marketTicker: "000990", yahooSymbol: "000990.KS" },
  { aliases: ["고영", "098460", "로봇", "검사장비"], category: "한국주식", currency: "KRW", description: "전자 제조 검사·자동화 장비 기업", id: "098460", label: "고영", marketTicker: "098460", yahooSymbol: "098460.KQ" },
  { aliases: ["레인보우로보틱스", "277810", "로봇"], category: "한국주식", currency: "KRW", description: "한국 협동로봇 대표 성장주", id: "277810", label: "레인보우로보틱스", marketTicker: "277810", yahooSymbol: "277810.KQ" },
  { aliases: ["로보스타", "090360", "로봇"], category: "한국주식", currency: "KRW", description: "산업용 로봇·자동화 기업", id: "090360", label: "로보스타", marketTicker: "090360", yahooSymbol: "090360.KQ" },
  { aliases: ["LIG넥스원", "079550", "방산", "로봇"], category: "한국주식", currency: "KRW", description: "방산·첨단 무기체계 대표 기업", id: "079550", label: "LIG넥스원", marketTicker: "079550", yahooSymbol: "079550.KS" },
  { aliases: ["LS ELECTRIC", "010120", "전력기기"], category: "한국주식", currency: "KRW", description: "전력기기·자동화 대표 기업", id: "010120", label: "LS ELECTRIC", marketTicker: "010120", yahooSymbol: "010120.KS" },
  { aliases: ["HD현대일렉트릭", "267260", "전력기기"], category: "한국주식", currency: "KRW", description: "전력기기·변압기 대표 기업", id: "267260", label: "HD현대일렉트릭", marketTicker: "267260", yahooSymbol: "267260.KS" },
  { aliases: ["삼성SDS", "018260", "AI", "클라우드"], category: "한국주식", currency: "KRW", description: "클라우드·IT서비스 대표 기업", id: "018260", label: "삼성SDS", marketTicker: "018260", yahooSymbol: "018260.KS" },
  { aliases: ["알테오젠", "196170"], category: "한국주식", currency: "KRW", description: "바이오 플랫폼 성장주", id: "196170", label: "알테오젠", marketTicker: "196170", yahooSymbol: "196170.KQ" },
  { aliases: ["에코프로", "086520"], category: "한국주식", currency: "KRW", description: "2차전지 소재 대표주", id: "086520", label: "에코프로", marketTicker: "086520", yahooSymbol: "086520.KQ" },
  { aliases: ["HMM", "011200"], category: "한국주식", currency: "KRW", description: "한국 대표 해운 기업", id: "011200", label: "HMM", marketTicker: "011200", yahooSymbol: "011200.KS" },
  { aliases: ["대한항공", "003490"], category: "한국주식", currency: "KRW", description: "한국 대표 항공사", id: "003490", label: "대한항공", marketTicker: "003490", yahooSymbol: "003490.KS" },
  { aliases: ["포스코퓨처엠", "003670"], category: "한국주식", currency: "KRW", description: "배터리 소재 대표 기업", id: "003670", label: "포스코퓨처엠", marketTicker: "003670", yahooSymbol: "003670.KS" },
  { aliases: ["삼성전기", "009150"], category: "한국주식", currency: "KRW", description: "MLCC·전자부품 대표 기업", id: "009150", label: "삼성전기", marketTicker: "009150", yahooSymbol: "009150.KS" },
  { aliases: ["LG전자", "066570"], category: "한국주식", currency: "KRW", description: "한국 대표 가전·전자 기업", id: "066570", label: "LG전자", marketTicker: "066570", yahooSymbol: "066570.KS" },
  { aliases: ["아모레퍼시픽", "090430"], category: "한국주식", currency: "KRW", description: "한국 대표 뷰티 기업", id: "090430", label: "아모레퍼시픽", marketTicker: "090430", yahooSymbol: "090430.KS" },
  { aliases: ["KT", "030200"], category: "한국주식", currency: "KRW", description: "한국 대표 통신 기업", id: "030200", label: "KT", marketTicker: "030200", yahooSymbol: "030200.KS" },
  { aliases: ["SK텔레콤", "017670"], category: "한국주식", currency: "KRW", description: "한국 대표 통신 기업", id: "017670", label: "SK텔레콤", marketTicker: "017670", yahooSymbol: "017670.KS" },
  { aliases: ["CJ제일제당", "097950"], category: "한국주식", currency: "KRW", description: "한국 대표 식품 기업", id: "097950", label: "CJ제일제당", marketTicker: "097950", yahooSymbol: "097950.KS" },
  { aliases: ["LG생활건강", "051900"], category: "한국주식", currency: "KRW", description: "한국 대표 생활소비재 기업", id: "051900", label: "LG생활건강", marketTicker: "051900", yahooSymbol: "051900.KS" },
  { aliases: ["메리츠금융지주", "138040"], category: "한국주식", currency: "KRW", description: "한국 대표 금융지주", id: "138040", label: "메리츠금융지주", marketTicker: "138040", yahooSymbol: "138040.KS" },
  { aliases: ["한국항공우주", "047810", "KAI"], category: "한국주식", currency: "KRW", description: "한국 대표 항공우주 기업", id: "047810", label: "한국항공우주", marketTicker: "047810", yahooSymbol: "047810.KS" },
  { aliases: ["현대로템", "064350"], category: "한국주식", currency: "KRW", description: "철도·방산 대표 기업", id: "064350", label: "현대로템", marketTicker: "064350", yahooSymbol: "064350.KS" },
  { aliases: ["엔씨소프트", "036570"], category: "한국주식", currency: "KRW", description: "한국 대표 게임 기업", id: "036570", label: "엔씨소프트", marketTicker: "036570", yahooSymbol: "036570.KS" },
  { aliases: ["미래에셋증권", "006800"], category: "한국주식", currency: "KRW", description: "한국 대표 증권사", id: "006800", label: "미래에셋증권", marketTicker: "006800", yahooSymbol: "006800.KS" },
  { aliases: ["삼성증권", "016360"], category: "한국주식", currency: "KRW", description: "한국 대표 증권사", id: "016360", label: "삼성증권", marketTicker: "016360", yahooSymbol: "016360.KS" },
  { aliases: ["삼성화재", "000810"], category: "한국주식", currency: "KRW", description: "한국 대표 손해보험사", id: "000810", label: "삼성화재", marketTicker: "000810", yahooSymbol: "000810.KS" },
  { aliases: ["삼성생명", "032830"], category: "한국주식", currency: "KRW", description: "한국 대표 생명보험사", id: "032830", label: "삼성생명", marketTicker: "032830", yahooSymbol: "032830.KS" },
  { aliases: ["한국금융지주", "071050"], category: "한국주식", currency: "KRW", description: "한국 대표 금융투자 지주", id: "071050", label: "한국금융지주", marketTicker: "071050", yahooSymbol: "071050.KS" },
  { aliases: ["키움증권", "039490"], category: "한국주식", currency: "KRW", description: "개인투자자 친화 증권사", id: "039490", label: "키움증권", marketTicker: "039490", yahooSymbol: "039490.KS" },
  { aliases: ["현대글로비스", "086280"], category: "한국주식", currency: "KRW", description: "물류·자동차 유통 대표 기업", id: "086280", label: "현대글로비스", marketTicker: "086280", yahooSymbol: "086280.KS" },
  { aliases: ["포스코인터내셔널", "047050"], category: "한국주식", currency: "KRW", description: "한국 대표 종합상사", id: "047050", label: "포스코인터내셔널", marketTicker: "047050", yahooSymbol: "047050.KS" },
  { aliases: ["한화솔루션", "009830"], category: "한국주식", currency: "KRW", description: "태양광·화학 대표 기업", id: "009830", label: "한화솔루션", marketTicker: "009830", yahooSymbol: "009830.KS" },
  { aliases: ["현대제철", "004020"], category: "한국주식", currency: "KRW", description: "한국 대표 철강 기업", id: "004020", label: "현대제철", marketTicker: "004020", yahooSymbol: "004020.KS" },
  { aliases: ["tiger 200", "102110"], category: "한국ETF", currency: "KRW", description: "한국 대표 지수 ETF", id: "102110", label: "TIGER 200", marketTicker: "102110", yahooSymbol: "102110.KS" },
  { aliases: ["kodex kosdaq150", "229200"], category: "한국ETF", currency: "KRW", description: "코스닥 대표 지수 ETF", id: "229200", label: "KODEX KOSDAQ150", marketTicker: "229200", yahooSymbol: "229200.KS" },
  { aliases: ["kodex 반도체", "091160"], category: "한국ETF", currency: "KRW", description: "한국 반도체 대표 ETF", id: "091160", label: "KODEX 반도체", marketTicker: "091160", yahooSymbol: "091160.KS" },
  { aliases: ["tiger 미국나스닥100", "133690"], category: "한국ETF", currency: "KRW", description: "미국 나스닥100 추종 ETF", id: "133690", label: "TIGER 미국나스닥100", marketTicker: "133690", yahooSymbol: "133690.KS" },
];
